# Makefile

# Compiler info
CC = ../gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin/arm-linux-gnueabihf-gcc
# Linker info
LD = ../gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin/arm-linux-gnueabihf-gcc
# Path info
OBJPATH = test
TARGET = $(OBJPATH)/gpio_test_out.arm
# Files info
SRC = main_gpio_test_out.c gpio_management.c
OBJ = $(OBJPATH)/main_gpio_test_out.o $(OBJPATH)/gpio_management.o


# Compiler options (all warnings, cpu type)
CCOPT = -Wall -mcpu=cortex-a8 
LDFLAGS = -mcpu=cortex-a8 -lm

# Targets
$(TARGET):	$(OBJ)
	$(LD) $(LDFLAGS) $(OBJ) -o $(TARGET) 
	
# Se ha bisogno di un file con estensione .o in ARMv7 (ARMv7/main.o) 
# prende il corrispondente file con estensione c (main.c) nella directory corrente
# ed esegue il comando corrispondente 	$(CC) $(CCOPT) -c main.c -o ARMv7/main.o) 
$(OBJPATH)/%.o: %.c
	$(CC) $(CCOPT) -c $< -o $@

	
clean:	
	rm $(OBJ) $(TARGET)

